// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActorRef } from "./ActorRef";

export type AddRoleMembershipRequest = { actor_ref: ActorRef, };
