// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentUsageResponse = { available: boolean, executor_type: string,
/**
 * The exact observed account context, or the configured exact key when
 * the Agent is pinned/credential-bound. Unpinned remote Agents have no
 * key until an execution-linked observation exists.
 */
account_key: string | null,
/**
 * Host/daemon that produced the returned observation, when known.
 */
daemon_id: string | null,
/**
 * Whether the server can perform a direct no-model usage probe for this
 * Agent. Remote CLI Agents receive usage from their execution host.
 */
manual_refresh_supported: boolean, shared_account: boolean, source: string | null, usage: Record<string, unknown> | null, captured_at: string | null, stale: boolean, message: string | null, };
