// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ArtifactKind = "plan" | "review_report" | "validation_report" | "diff" | "patch" | "summary" | "design_document" | "investigation" | "api_contract" | "test_report";
