// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConnectEmbeddedAgentRequest = { name: string, description: string | null, provider: string, base_url: string, model: string, credential_label: string, credential: string, system_prompt: string | null, account_permission_ceiling: Record<string, unknown> | null, tool_policy: Record<string, unknown> | null, context_tokens: number | null, max_input_tokens: number | null, max_output_tokens: number | null, };
