// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConversationMessageRole } from "./ConversationMessageRole";
import type { ConversationMessageStatus } from "./ConversationMessageStatus";

export type ConversationMessageResponse = { id: string, conversation_id: string, role: ConversationMessageRole, content: string, status: ConversationMessageStatus, model: string | null, token_usage_json: Record<string, unknown> | null, duration_ms: bigint | null, error: string | null, sequence: bigint, created_at: string, updated_at: string, };
