// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConversationStatus } from "./ConversationStatus";

export type ConversationResponse = { id: string, project_id: string, agent_id: string | null, title: string, status: ConversationStatus, system_prompt: string | null, message_count: bigint, last_message_at: string | null, agent_session_id: string | null, version: bigint, created_at: string, updated_at: string, };
