// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactKind } from "./ArtifactKind";
import type { ArtifactStorageKind } from "./ArtifactStorageKind";

export type CreateArtifactRequest = { kind: ArtifactKind, storage_kind: ArtifactStorageKind, content: string | null, content_ref: string | null, metadata: Record<string, unknown>, digest: string | null, producer_execution_id: string, };
