// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoordinationMode } from "./CoordinationMode";

export type CreateTaskRoleRequest = { role: string, coordination_mode: CoordinationMode, policy: Record<string, unknown> | null, };
