// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateConversationRequest = { agent_id: string, title: string | null, system_prompt: string | null, };
