// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DecisionOutcome } from "./DecisionOutcome";

export type CreateDecisionRequest = { proposal_id: string, proposal_version: bigint, outcome: DecisionOutcome, rationale: string, policy_ref: string | null, policy_version: bigint | null, policy_digest: string | null, };
