// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CollaborationTarget } from "./CollaborationTarget";
import type { HandoffIntent } from "./HandoffIntent";

export type CreateHandoffRequest = { source_role_id: string | null, target: CollaborationTarget, intent: HandoffIntent, parent_execution_id: string | null, expected_policy_ref: string | null, artifact_ids: Array<string>, };
