// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActorRef } from "./ActorRef";
import type { CreateWorkUnitProvenance } from "./CreateWorkUnitProvenance";

export type CreateWorkUnitRequest = { title: string, scope: string, role: string, parent_work_unit_id: string | null, assigned_actor: ActorRef | null, requires_integration: boolean, provenance: CreateWorkUnitProvenance | null, };
