// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RemoteTokenUsage } from "./RemoteTokenUsage";

export type ExecutionTerminalNotification = { execution_id: string, exit_code: number | null, signal: string | null, error: string | null, ts: string, status: string | null, agent_session_id: string | null, summary: string | null, after_sha: string | null, usage: RemoteTokenUsage | null, };
