// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HarnessInvocation } from "./HarnessInvocation";

export type ExecutionStartParams = { task_id: string, execution_id: string, role: string, workspace_path: string, executor_type: string, executor_config: unknown, prompt: unknown, invocation: HarnessInvocation, max_turns: number | null, };
