// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExecutionTerminalNotification = { execution_id: string, exit_code: number | null, signal: string | null, error: string | null, ts: string, };
