// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HandoffIntent = "rework" | "delegation" | "question" | "answer" | "investigate" | "decision_request";
