// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActorRef } from "./ActorRef";
import type { CollaborationTarget } from "./CollaborationTarget";
import type { HandoffIntent } from "./HandoffIntent";
import type { HandoffStatus } from "./HandoffStatus";

export type HandoffResponse = { id: string, task_id: string, created_by: ActorRef, source_role_id: string | null, target: CollaborationTarget, intent: HandoffIntent, parent_execution_id: string | null, expected_policy_ref: string | null, status: HandoffStatus, version: bigint, artifact_ids: Array<string>, created_at: string, updated_at: string, };
