// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapabilitySupport } from "./CapabilitySupport";

/**
 * Effective, non-secret capability evidence for one normalized harness
 * configuration. Unknown is always fail-closed.
 */
export type HarnessCapabilities = { resume: CapabilitySupport, cancel: CapabilitySupport, structured_events: CapabilitySupport, usage_reporting: CapabilitySupport, account_usage_observation: CapabilitySupport, model_selection: CapabilitySupport, reasoning_controls: CapabilitySupport, approval_policy: CapabilitySupport, sandbox_controls: CapabilitySupport, planning: CapabilitySupport, review_mode: CapabilitySupport, fork: CapabilitySupport, steer: CapabilitySupport, pause_resume: CapabilitySupport, compaction: CapabilitySupport, subagents: CapabilitySupport, };
