// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A typed readiness acknowledgement from the Main discovery protocol. The
 * Project creation request remains a separate normal Project mutation so its
 * atomic chat/binding transaction is reused rather than duplicated here.
 */
export type ReadyProductGenesisRequest = { expected_version: bigint, };
