// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The executor candidate that actually ran a remote execution.
 */
import type { HarnessCapabilities } from "./HarnessCapabilities";
import type { EffectiveExecutionPolicy } from "./EffectiveExecutionPolicy";

export type RemoteResolvedCandidate = { candidate_key: string, executor_type: string, config: Record<string, unknown>, harness_capabilities: HarnessCapabilities, effective_policy: EffectiveExecutionPolicy | null, };
