// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActorRef } from "./ActorRef";
import type { RoleMembershipStatus } from "./RoleMembershipStatus";

export type RoleMembershipResponse = { id: string, task_role_id: string, actor_ref: ActorRef, status: RoleMembershipStatus, version: bigint, created_at: string, updated_at: string, ended_at: string | null, };
