// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlanArtifactDetail } from "./PlanArtifactDetail";
import type { TaskPlanRevisionSummary } from "./TaskPlanRevisionSummary";

export type TaskPlanHistoryResponse = { current: PlanArtifactDetail | null, revisions: Array<TaskPlanRevisionSummary>, };
