// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TaskPlanRevisionSummary = { id: string, revision: bigint, checkpoint: string, content_digest: string, created_at: string, };
