// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Task } from "./Task";

export type TasksResponse = { items: Array<Task>, next_cursor: string | null, };
