// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoordinationMode } from "./CoordinationMode";
import type { RoleMembershipResponse } from "./RoleMembershipResponse";

export type TaskRoleResponse = { id: string, task_id: string, role: string, coordination_mode: CoordinationMode | null, policy: Record<string, unknown>, version: bigint, members: Array<RoleMembershipResponse>, created_at: string, updated_at: string, };
