// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConversationStatus } from "./ConversationStatus";

export type UpdateConversationRequest = { version: bigint, title: string | null, agent_id: string | null, system_prompt: string | null, status: ConversationStatus | null, };
