// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoordinationMode } from "./CoordinationMode";

export type UpdateTaskRoleRequest = { expected_version: bigint, coordination_mode: CoordinationMode | null, policy: Record<string, unknown> | null, };
