// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActorRef } from "./ActorRef";
import type { WorkUnitProvenance } from "./WorkUnitProvenance";
import type { WorkUnitReadinessResponse } from "./WorkUnitReadinessResponse";
import type { WorkUnitStatus } from "./WorkUnitStatus";

export type WorkUnitResponse = { id: string, task_id: string, parent_work_unit_id: string | null, title: string, scope: string, status: WorkUnitStatus, role: string, assigned_actor: ActorRef | null, requires_integration: boolean, provenance: WorkUnitProvenance | null, created_by: ActorRef, version: bigint, created_at: string, updated_at: string, readiness: WorkUnitReadinessResponse, };
