// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkUnitDependencyResponse = { work_unit_id: string, depends_on_work_unit_id: string, satisfied: boolean, created_at: string, };
