// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkUnitReadinessResponse = { runnable: boolean, ready_for_allocation: boolean, active_execution_ids: Array<string>, unsatisfied_dependency_ids: Array<string>, awaiting_integration: boolean, };
