#![forbid(unsafe_code)]

pub mod assignee;
mod auth;

mod actor;
mod analytics;
mod core;
mod daemon_transport;
mod execution;
mod git;
mod integration;
mod lists;
mod mcp;
mod memory;
mod oauth;
mod operations;
mod project_hooks;
mod repo_review;
mod requests;
mod runtime;
mod settings;
mod terminal;
mod workflow;

pub use actor::*;
pub use analytics::*;
pub use auth::*;
pub use core::*;
pub use daemon_transport::*;
pub use execution::*;
pub use git::*;
pub use integration::*;
pub use lists::*;
pub use mcp::*;
pub use memory::*;
pub use oauth::*;
pub use operations::*;
pub use project_hooks::*;
pub use repo_review::*;
pub use requests::*;
pub use runtime::*;
pub use settings::*;
pub use terminal::*;
pub use workflow::*;

#[test]
#[ignore = "manual type export for the web client"]
fn export_typescript() {
    use ts_rs::TS;

    let out_dir =
        std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../web/src/types/generated");
    std::fs::create_dir_all(&out_dir).expect("create types output directory");
    std::env::set_current_dir(&out_dir).expect("switch to types output directory");

    TaskType::export().expect("export TaskType");
    WorkMode::export().expect("export WorkMode");
    CreateRepoRequest::export().expect("export CreateRepoRequest");
    UpdateRepoRequest::export().expect("export UpdateRepoRequest");
    RepoResponse::export().expect("export RepoResponse");
    RepoSyncResponse::export().expect("export RepoSyncResponse");
    FsEntry::export().expect("export FsEntry");
    FsListResponse::export().expect("export FsListResponse");
    BranchListResponse::export().expect("export BranchListResponse");
    ReviewConfig::export().expect("export ReviewConfig");
    RetryBudgets::export().expect("export RetryBudgets");
    AutomaticRecoverySettings::export().expect("export AutomaticRecoverySettings");
    LifecycleEvent::export().expect("export LifecycleEvent");
    LifecycleHookDef::export().expect("export LifecycleHookDef");
    ProjectSettings::export().expect("export ProjectSettings");
    LifecycleHookTestResponse::export().expect("export LifecycleHookTestResponse");
    TaskMetadata::export().expect("export TaskMetadata");
    Task::export().expect("export Task");
    StopReason::export().expect("export StopReason");
    ResumePolicy::export().expect("export ResumePolicy");
    RecoveryAction::export().expect("export RecoveryAction");
    ExecutionBehaviorKind::export().expect("export ExecutionBehaviorKind");
    ExecutionBehavior::export().expect("export ExecutionBehavior");
    ExecutionActionKind::export().expect("export ExecutionActionKind");
    ExecutionAction::export().expect("export ExecutionAction");
    BlockingArtifact::export().expect("export BlockingArtifact");
    TaskBlockingAnnotation::export().expect("export TaskBlockingAnnotation");
    InterruptionMetadata::export().expect("export InterruptionMetadata");
    TaskAnnotation::export().expect("export TaskAnnotation");
    TaskExecutionObservability::export().expect("export TaskExecutionObservability");
    TaskResponse::export().expect("export TaskResponse");
    ExecutionUsageResponse::export().expect("export ExecutionUsageResponse");
    TaskUsageSummaryResponse::export().expect("export TaskUsageSummaryResponse");
    PromptPreviewResponse::export().expect("export PromptPreviewResponse");
    MemorySearchQuery::export().expect("export MemorySearchQuery");
    MemoryGetQuery::export().expect("export MemoryGetQuery");
    MemorySearchResultDto::export().expect("export MemorySearchResultDto");
    MemorySearchResponse::export().expect("export MemorySearchResponse");
    TerminalSessionStatus::export().expect("export TerminalSessionStatus");
    TerminalSessionResponse::export().expect("export TerminalSessionResponse");
    CreateTerminalSessionRequest::export().expect("export CreateTerminalSessionRequest");
    ResizeTerminalSessionRequest::export().expect("export ResizeTerminalSessionRequest");
    TerminalAttachTokenResponse::export().expect("export TerminalAttachTokenResponse");
    TerminalAvailability::export().expect("export TerminalAvailability");
    TerminalClientFrame::export().expect("export TerminalClientFrame");
    TerminalServerFrame::export().expect("export TerminalServerFrame");
    TasksResponse::export().expect("export TasksResponse");
    MoveTaskRequest::export().expect("export MoveTaskRequest");
    MoveTaskResponse::export().expect("export MoveTaskResponse");
    OperationConflictDetails::export().expect("export OperationConflictDetails");
    TaskVersionConflictDetails::export().expect("export TaskVersionConflictDetails");
    BoardRevisionConflictDetails::export().expect("export BoardRevisionConflictDetails");
    TaskMovedEventPayload::export().expect("export TaskMovedEventPayload");
    Agent::export().expect("export Agent");
    AgentsResponse::export().expect("export AgentsResponse");
    Project::export().expect("export Project");
    ProjectHookRule::export().expect("export ProjectHookRule");
    ProjectHookTrigger::export().expect("export ProjectHookTrigger");
    ProjectHookAction::export().expect("export ProjectHookAction");
    ProjectHookRunStatus::export().expect("export ProjectHookRunStatus");
    ProjectHookRunResponse::export().expect("export ProjectHookRunResponse");
    ProjectHookRunsResponse::export().expect("export ProjectHookRunsResponse");
    ProjectAgentLinkResponse::export().expect("export ProjectAgentLinkResponse");
    ProjectsResponse::export().expect("export ProjectsResponse");
    CreateProjectAgentLinkRequest::export().expect("export CreateProjectAgentLinkRequest");
    TransitionSource::export().expect("export TransitionSource");
    TransitionTaskRequest::export().expect("export TransitionTaskRequest");
    AuthorType::export().expect("export AuthorType");
    TaskMediaResponse::export().expect("export TaskMediaResponse");
    RecoverTaskRequest::export().expect("export RecoverTaskRequest");
    TestLifecycleHookRequest::export().expect("export TestLifecycleHookRequest");
    CreateCommentRequest::export().expect("export CreateCommentRequest");
    StateKind::export().expect("export StateKind");
    CleanupPolicy::export().expect("export CleanupPolicy");
    FailurePolicy::export().expect("export FailurePolicy");
    HookAudience::export().expect("export HookAudience");
    GateConfig::export().expect("export GateConfig");
    HookSpec::export().expect("export HookSpec");
    StateHooks::export().expect("export StateHooks");
    StateDefinition::export().expect("export StateDefinition");
    WorkflowTrigger::export().expect("export WorkflowTrigger");
    WorkflowExecutionStrategy::export().expect("export WorkflowExecutionStrategy");
    WorkflowPromptConfig::export().expect("export WorkflowPromptConfig");
    WorkflowDispatch::export().expect("export WorkflowDispatch");
    WorkflowTriggerDefinition::export().expect("export WorkflowTriggerDefinition");
    RoleDefinition::export().expect("export RoleDefinition");
    WorkflowConfigValueType::export().expect("export WorkflowConfigValueType");
    WorkflowConfigBinding::export().expect("export WorkflowConfigBinding");
    WorkflowConfigField::export().expect("export WorkflowConfigField");
    PromptBuilderRegistryEntry::export().expect("export PromptBuilderRegistryEntry");
    WorkflowDefinition::export().expect("export WorkflowDefinition");
    WorkflowTemplateSummary::export().expect("export WorkflowTemplateSummary");
    WorkflowTemplateResponse::export().expect("export WorkflowTemplateResponse");
    SaveWorkflowTemplateRequest::export().expect("export SaveWorkflowTemplateRequest");
    UpdateProjectWorkflowRequest::export().expect("export UpdateProjectWorkflowRequest");
    TaskRoleAssignmentResponse::export().expect("export TaskRoleAssignmentResponse");
    AssignRoleRequest::export().expect("export AssignRoleRequest");
    assignee::AssigneeKind::export().expect("export AssigneeKind");
    DefaultRoleAssignment::export().expect("export DefaultRoleAssignment");
    InitialRoleAssignment::export().expect("export InitialRoleAssignment");
    TransitionLogEntry::export().expect("export TransitionLogEntry");
    HookResultEntry::export().expect("export HookResultEntry");
    ReorderSubtasksRequest::export().expect("export ReorderSubtasksRequest");
    OperatorSeverity::export().expect("export OperatorSeverity");
    OperatorStatusResponse::export().expect("export OperatorStatusResponse");
    ActiveExecutionSummary::export().expect("export ActiveExecutionSummary");
    BlockedTaskSummary::export().expect("export BlockedTaskSummary");
    DaemonIssueSummary::export().expect("export DaemonIssueSummary");
    DaemonPressureSummary::export().expect("export DaemonPressureSummary");
    AgentPressureSummary::export().expect("export AgentPressureSummary");
    WorkspaceCleanupSummary::export().expect("export WorkspaceCleanupSummary");
    RetryPressureSummary::export().expect("export RetryPressureSummary");
    TokenTotalsSummary::export().expect("export TokenTotalsSummary");
    OperationsRefreshResponse::export().expect("export OperationsRefreshResponse");
    UsageSummary::export().expect("export UsageSummary");
    RecentErrorSummary::export().expect("export RecentErrorSummary");
    PlanArtifactDetail::export().expect("export PlanArtifactDetail");
    PlanChecklistItem::export().expect("export PlanChecklistItem");
    EffectiveExecutionPolicy::export().expect("export EffectiveExecutionPolicy");
    PlanProgressSummary::export().expect("export PlanProgressSummary");
    SettingsResponse::export().expect("export SettingsResponse");
    ForgeSettingResponse::export().expect("export ForgeSettingResponse");
    UpdateSettingsRequest::export().expect("export UpdateSettingsRequest");
    UpdateForgePathsRequest::export().expect("export UpdateForgePathsRequest");
    UpdateServerSettingsRequest::export().expect("export UpdateServerSettingsRequest");
    UpdateWorkspaceSettingsRequest::export().expect("export UpdateWorkspaceSettingsRequest");
    UpdateAgentSettingsRequest::export().expect("export UpdateAgentSettingsRequest");
    RegisterRequest::export().expect("export RegisterRequest");
    LoginRequest::export().expect("export LoginRequest");
    RefreshRequest::export().expect("export RefreshRequest");
    LogoutRequest::export().expect("export LogoutRequest");
    AuthResponse::export().expect("export AuthResponse");
    UserResponse::export().expect("export UserResponse");
    UpdateProfileRequest::export().expect("export UpdateProfileRequest");
    OAuthRegisterRequest::export().expect("export OAuthRegisterRequest");
    OAuthRegisterResponse::export().expect("export OAuthRegisterResponse");
    OAuthApproveRequest::export().expect("export OAuthApproveRequest");
    OAuthDecision::export().expect("export OAuthDecision");
    OAuthApproveResponse::export().expect("export OAuthApproveResponse");
    OAuthAuthorizeContext::export().expect("export OAuthAuthorizeContext");
    OAuthErrorResponse::export().expect("export OAuthErrorResponse");
}
