#![forbid(unsafe_code)]

pub mod assignee;
mod auth;

mod actor;
mod agent_chats;
mod analytics;
mod coordination;
mod core;
mod daemon_transport;
mod execution;
mod git;
mod integration;
mod lists;
mod mcp;
mod memory;
mod mission_control;
mod oauth;
mod operations;
mod product_genesis;
mod project_hooks;
mod repo_review;
mod requests;
mod runtime;
mod settings;
mod terminal;
mod workflow;

pub use actor::*;
pub use agent_chats::*;
pub use analytics::*;
pub use auth::*;
pub use coordination::*;
pub use core::*;
pub use daemon_transport::*;
pub use execution::*;
pub use git::*;
pub use integration::*;
pub use lists::*;
pub use mcp::*;
pub use memory::*;
pub use mission_control::*;
pub use oauth::*;
pub use operations::*;
pub use product_genesis::*;
pub use project_hooks::*;
pub use repo_review::*;
pub use requests::*;
pub use runtime::*;
pub use settings::*;
pub use terminal::*;
pub use workflow::*;

#[test]
#[ignore = "manual type export for the web client"]
fn export_typescript() {
    use ts_rs::TS;

    let out_dir =
        std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../web/src/types/generated");
    std::fs::create_dir_all(&out_dir).expect("create types output directory");
    std::env::set_current_dir(&out_dir).expect("switch to types output directory");

    TaskType::export().expect("export TaskType");
    ProductMaturity::export().expect("export ProductMaturity");
    ProductGenesisLifecycle::export().expect("export ProductGenesisLifecycle");
    ProductGenesisSession::export().expect("export ProductGenesisSession");
    StartProductGenesisRequest::export().expect("export StartProductGenesisRequest");
    ProductGenesisStartResponse::export().expect("export ProductGenesisStartResponse");
    ProductGenesisActiveResponse::export().expect("export ProductGenesisActiveResponse");
    CancelProductGenesisRequest::export().expect("export CancelProductGenesisRequest");
    ReadyProductGenesisRequest::export().expect("export ReadyProductGenesisRequest");
    WorkMode::export().expect("export WorkMode");
    CreateRepoRequest::export().expect("export CreateRepoRequest");
    UpdateRepoRequest::export().expect("export UpdateRepoRequest");
    RepoResponse::export().expect("export RepoResponse");
    RepoSyncResponse::export().expect("export RepoSyncResponse");
    FsEntry::export().expect("export FsEntry");
    FsListResponse::export().expect("export FsListResponse");
    BranchListResponse::export().expect("export BranchListResponse");
    ReviewConfig::export().expect("export ReviewConfig");
    RetryBudgets::export().expect("export RetryBudgets");
    AutomaticRecoverySettings::export().expect("export AutomaticRecoverySettings");
    LifecycleEvent::export().expect("export LifecycleEvent");
    LifecycleHookDef::export().expect("export LifecycleHookDef");
    ProjectSettings::export().expect("export ProjectSettings");
    LifecycleHookTestResponse::export().expect("export LifecycleHookTestResponse");
    TaskMetadata::export().expect("export TaskMetadata");
    Task::export().expect("export Task");
    TaskAction::export().expect("export TaskAction");
    TaskActionsResponse::export().expect("export TaskActionsResponse");
    StopReason::export().expect("export StopReason");
    ResumePolicy::export().expect("export ResumePolicy");
    RecoveryAction::export().expect("export RecoveryAction");
    ExecutionBehaviorKind::export().expect("export ExecutionBehaviorKind");
    ExecutionBehavior::export().expect("export ExecutionBehavior");
    ExecutionActionKind::export().expect("export ExecutionActionKind");
    ExecutionAction::export().expect("export ExecutionAction");
    BlockingArtifact::export().expect("export BlockingArtifact");
    TaskBlockingAnnotation::export().expect("export TaskBlockingAnnotation");
    InterruptionMetadata::export().expect("export InterruptionMetadata");
    TaskAnnotation::export().expect("export TaskAnnotation");
    TaskExecutionObservability::export().expect("export TaskExecutionObservability");
    TaskResponse::export().expect("export TaskResponse");
    ExecutionUsageResponse::export().expect("export ExecutionUsageResponse");
    TaskUsageSummaryResponse::export().expect("export TaskUsageSummaryResponse");
    PromptPreviewResponse::export().expect("export PromptPreviewResponse");
    MemorySearchQuery::export().expect("export MemorySearchQuery");
    MemoryGetQuery::export().expect("export MemoryGetQuery");
    MemorySearchResultDto::export().expect("export MemorySearchResultDto");
    MemorySearchResponse::export().expect("export MemorySearchResponse");
    MemoryPublicationRequest::export().expect("export MemoryPublicationRequest");
    MemoryLifecycleRequest::export().expect("export MemoryLifecycleRequest");
    MemoryLifecycleResponse::export().expect("export MemoryLifecycleResponse");
    MemoryProvenanceResponse::export().expect("export MemoryProvenanceResponse");
    ContextManifestQuery::export().expect("export ContextManifestQuery");
    ContextManifestListQuery::export().expect("export ContextManifestListQuery");
    ContextManifestSourceResponse::export().expect("export ContextManifestSourceResponse");
    ContextManifestResponse::export().expect("export ContextManifestResponse");
    ContextManifestListResponse::export().expect("export ContextManifestListResponse");
    MemoryProvenanceQuery::export().expect("export MemoryProvenanceQuery");
    AttentionLifecycle::export().expect("export AttentionLifecycle");
    AttentionCategory::export().expect("export AttentionCategory");
    AttentionItem::export().expect("export AttentionItem");
    AttentionListResponse::export().expect("export AttentionListResponse");
    AttentionConsumerHealthResponse::export().expect("export AttentionConsumerHealthResponse");
    AttentionMutationRequest::export().expect("export AttentionMutationRequest");
    AttentionSnoozeRequest::export().expect("export AttentionSnoozeRequest");
    MissionControlWorkItem::export().expect("export MissionControlWorkItem");
    MissionControlAgentHealth::export().expect("export MissionControlAgentHealth");
    MissionControlRecentOutcome::export().expect("export MissionControlRecentOutcome");
    MissionControlCapacity::export().expect("export MissionControlCapacity");
    MissionControlHomeResponse::export().expect("export MissionControlHomeResponse");
    MissionControlQuery::export().expect("export MissionControlQuery");
    AgentDetailResponse::export().expect("export AgentDetailResponse");
    AgentBindingSummary::export().expect("export AgentBindingSummary");
    AgentUsageSummary::export().expect("export AgentUsageSummary");
    AgentScopeSummary::export().expect("export AgentScopeSummary");
    AgentSessionSummary::export().expect("export AgentSessionSummary");
    AgentContinuityHealth::export().expect("export AgentContinuityHealth");
    TerminalSessionStatus::export().expect("export TerminalSessionStatus");
    TerminalSessionResponse::export().expect("export TerminalSessionResponse");
    CreateTerminalSessionRequest::export().expect("export CreateTerminalSessionRequest");
    ResizeTerminalSessionRequest::export().expect("export ResizeTerminalSessionRequest");
    TerminalAttachTokenResponse::export().expect("export TerminalAttachTokenResponse");
    TerminalAvailability::export().expect("export TerminalAvailability");
    TerminalClientFrame::export().expect("export TerminalClientFrame");
    TerminalServerFrame::export().expect("export TerminalServerFrame");
    TasksResponse::export().expect("export TasksResponse");
    MoveTaskRequest::export().expect("export MoveTaskRequest");
    MoveTaskResponse::export().expect("export MoveTaskResponse");
    OperationConflictDetails::export().expect("export OperationConflictDetails");
    TaskVersionConflictDetails::export().expect("export TaskVersionConflictDetails");
    BoardRevisionConflictDetails::export().expect("export BoardRevisionConflictDetails");
    TaskMovedEventPayload::export().expect("export TaskMovedEventPayload");
    Agent::export().expect("export Agent");
    AgentStatus::export().expect("export AgentStatus");
    AgentResponse::export().expect("export AgentResponse");
    AgentsResponse::export().expect("export AgentsResponse");
    Project::export().expect("export Project");
    ProjectHookRule::export().expect("export ProjectHookRule");
    ProjectHookTrigger::export().expect("export ProjectHookTrigger");
    ProjectHookAction::export().expect("export ProjectHookAction");
    ProjectHookRunStatus::export().expect("export ProjectHookRunStatus");
    ProjectHookRunResponse::export().expect("export ProjectHookRunResponse");
    ProjectHookRunsResponse::export().expect("export ProjectHookRunsResponse");
    ProjectsResponse::export().expect("export ProjectsResponse");
    AgentBindingState::export().expect("export AgentBindingState");
    AgentChatKind::export().expect("export AgentChatKind");
    AgentChatStatus::export().expect("export AgentChatStatus");
    AgentChatMessageAuthorType::export().expect("export AgentChatMessageAuthorType");
    AgentChatMessageStatus::export().expect("export AgentChatMessageStatus");
    AgentChatTurnStatus::export().expect("export AgentChatTurnStatus");
    AgentHandoffStatus::export().expect("export AgentHandoffStatus");
    MainAgentBindingResponse::export().expect("export MainAgentBindingResponse");
    ProjectAgentBindingResponse::export().expect("export ProjectAgentBindingResponse");
    SetMainAgentBindingRequest::export().expect("export SetMainAgentBindingRequest");
    SetProjectAgentBindingRequest::export().expect("export SetProjectAgentBindingRequest");
    AgentChatResponse::export().expect("export AgentChatResponse");
    AgentChatDetailResponse::export().expect("export AgentChatDetailResponse");
    AgentChatSwitcherItem::export().expect("export AgentChatSwitcherItem");
    AgentChatSwitcherResponse::export().expect("export AgentChatSwitcherResponse");
    AgentChatMessageResponse::export().expect("export AgentChatMessageResponse");
    AgentChatTurnJobResponse::export().expect("export AgentChatTurnJobResponse");
    SendAgentChatMessageRequest::export().expect("export SendAgentChatMessageRequest");
    SendAgentChatMessageResponse::export().expect("export SendAgentChatMessageResponse");
    CancelAgentChatTurnRequest::export().expect("export CancelAgentChatTurnRequest");
    CreateAgentHandoffRequest::export().expect("export CreateAgentHandoffRequest");
    AgentHandoffResponse::export().expect("export AgentHandoffResponse");
    AgentChatListQuery::export().expect("export AgentChatListQuery");
    AgentChatListResponse::export().expect("export AgentChatListResponse");
    AgentChatMessagesQuery::export().expect("export AgentChatMessagesQuery");
    AgentChatMessageListResponse::export().expect("export AgentChatMessageListResponse");
    ConnectEmbeddedAgentRequest::export().expect("export ConnectEmbeddedAgentRequest");
    ConnectEmbeddedProfileRequest::export().expect("export ConnectEmbeddedProfileRequest");
    CanonicalScopeRequest::export().expect("export CanonicalScopeRequest");
    CreateAgentSessionRequest::export().expect("export CreateAgentSessionRequest");
    SessionVersionRequest::export().expect("export SessionVersionRequest");
    SteerAgentSessionRequest::export().expect("export SteerAgentSessionRequest");
    CredentialHandleResponse::export().expect("export CredentialHandleResponse");
    AgentProfileResponse::export().expect("export AgentProfileResponse");
    AgentConnectionHealthResponse::export().expect("export AgentConnectionHealthResponse");
    AgentSessionResponse::export().expect("export AgentSessionResponse");
    ProtectedInteractionSummaryResponse::export()
        .expect("export ProtectedInteractionSummaryResponse");
    ProtectedInteractionAnswerRequest::export().expect("export ProtectedInteractionAnswerRequest");
    ProtectedInteractionAnswerValue::export().expect("export ProtectedInteractionAnswerValue");
    ProtectedInteractionCancelRequest::export().expect("export ProtectedInteractionCancelRequest");
    ConnectedEmbeddedAgentResponse::export().expect("export ConnectedEmbeddedAgentResponse");
    ConnectedEmbeddedProfileResponse::export().expect("export ConnectedEmbeddedProfileResponse");
    EffectivePermissionsResponse::export().expect("export EffectivePermissionsResponse");
    CommitmentResponse::export().expect("export CommitmentResponse");
    CreateCommitmentRequest::export().expect("export CreateCommitmentRequest");
    UpdateCommitmentRequest::export().expect("export UpdateCommitmentRequest");
    CompleteCommitmentRequest::export().expect("export CompleteCommitmentRequest");
    TransferCommitmentRequest::export().expect("export TransferCommitmentRequest");
    CommitmentEvidenceResponse::export().expect("export CommitmentEvidenceResponse");
    CoordinationListQuery::export().expect("export CoordinationListQuery");
    InboxItemResponse::export().expect("export InboxItemResponse");
    UpdateInboxItemRequest::export().expect("export UpdateInboxItemRequest");
    AskQuestionRequest::export().expect("export AskQuestionRequest");
    QuestionResponse::export().expect("export QuestionResponse");
    AnswerQuestionRequest::export().expect("export AnswerQuestionRequest");
    AgentActionResponse::export().expect("export AgentActionResponse");
    ProposeActionRequest::export().expect("export ProposeActionRequest");
    TaskProposalRequest::export().expect("export TaskProposalRequest");
    ApproveActionRequest::export().expect("export ApproveActionRequest");
    ExecuteActionRequest::export().expect("export ExecuteActionRequest");
    ExecuteTaskProposalRequest::export().expect("export ExecuteTaskProposalRequest");
    ActionExecutionResponse::export().expect("export ActionExecutionResponse");
    TaskProposalExecutionResponse::export().expect("export TaskProposalExecutionResponse");
    TransitionSource::export().expect("export TransitionSource");
    TransitionTaskRequest::export().expect("export TransitionTaskRequest");
    AuthorType::export().expect("export AuthorType");
    TaskMediaResponse::export().expect("export TaskMediaResponse");
    RecoverTaskRequest::export().expect("export RecoverTaskRequest");
    TaskActionRequest::export().expect("export TaskActionRequest");
    TestLifecycleHookRequest::export().expect("export TestLifecycleHookRequest");
    CreateCommentRequest::export().expect("export CreateCommentRequest");
    StateKind::export().expect("export StateKind");
    CleanupPolicy::export().expect("export CleanupPolicy");
    FailurePolicy::export().expect("export FailurePolicy");
    HookAudience::export().expect("export HookAudience");
    GateConfig::export().expect("export GateConfig");
    HookSpec::export().expect("export HookSpec");
    StateHooks::export().expect("export StateHooks");
    CanonicalPhase::export().expect("export CanonicalPhase");
    StateDefinition::export().expect("export StateDefinition");
    WorkflowTrigger::export().expect("export WorkflowTrigger");
    WorkflowExecutionStrategy::export().expect("export WorkflowExecutionStrategy");
    WorkflowPromptConfig::export().expect("export WorkflowPromptConfig");
    WorkflowDispatch::export().expect("export WorkflowDispatch");
    WorkflowTriggerDefinition::export().expect("export WorkflowTriggerDefinition");
    RoleDefinition::export().expect("export RoleDefinition");
    WorkflowConfigValueType::export().expect("export WorkflowConfigValueType");
    WorkflowConfigBinding::export().expect("export WorkflowConfigBinding");
    WorkflowConfigField::export().expect("export WorkflowConfigField");
    PromptBuilderRegistryEntry::export().expect("export PromptBuilderRegistryEntry");
    WorkflowDefinition::export().expect("export WorkflowDefinition");
    WorkflowTemplateSummary::export().expect("export WorkflowTemplateSummary");
    WorkflowTemplateResponse::export().expect("export WorkflowTemplateResponse");
    SaveWorkflowTemplateRequest::export().expect("export SaveWorkflowTemplateRequest");
    UpdateProjectWorkflowRequest::export().expect("export UpdateProjectWorkflowRequest");
    TaskRoleAssignmentResponse::export().expect("export TaskRoleAssignmentResponse");
    AssignRoleRequest::export().expect("export AssignRoleRequest");
    assignee::AssigneeKind::export().expect("export AssigneeKind");
    DefaultRoleAssignment::export().expect("export DefaultRoleAssignment");
    InitialRoleAssignment::export().expect("export InitialRoleAssignment");
    TransitionLogEntry::export().expect("export TransitionLogEntry");
    HookResultEntry::export().expect("export HookResultEntry");
    ReorderSubtasksRequest::export().expect("export ReorderSubtasksRequest");
    OperatorSeverity::export().expect("export OperatorSeverity");
    OperatorStatusResponse::export().expect("export OperatorStatusResponse");
    ActiveExecutionSummary::export().expect("export ActiveExecutionSummary");
    BlockedTaskSummary::export().expect("export BlockedTaskSummary");
    DaemonIssueSummary::export().expect("export DaemonIssueSummary");
    DaemonPressureSummary::export().expect("export DaemonPressureSummary");
    AgentPressureSummary::export().expect("export AgentPressureSummary");
    WorkspaceCleanupSummary::export().expect("export WorkspaceCleanupSummary");
    RetryPressureSummary::export().expect("export RetryPressureSummary");
    TokenTotalsSummary::export().expect("export TokenTotalsSummary");
    OperationsRefreshResponse::export().expect("export OperationsRefreshResponse");
    UsageSummary::export().expect("export UsageSummary");
    RecentErrorSummary::export().expect("export RecentErrorSummary");
    PlanArtifactDetail::export().expect("export PlanArtifactDetail");
    PlanChecklistItem::export().expect("export PlanChecklistItem");
    EffectiveExecutionPolicy::export().expect("export EffectiveExecutionPolicy");
    PlanProgressSummary::export().expect("export PlanProgressSummary");
    SettingsResponse::export().expect("export SettingsResponse");
    ForgeSettingResponse::export().expect("export ForgeSettingResponse");
    UpdateSettingsRequest::export().expect("export UpdateSettingsRequest");
    UpdateForgePathsRequest::export().expect("export UpdateForgePathsRequest");
    UpdateServerSettingsRequest::export().expect("export UpdateServerSettingsRequest");
    UpdateWorkspaceSettingsRequest::export().expect("export UpdateWorkspaceSettingsRequest");
    UpdateAgentSettingsRequest::export().expect("export UpdateAgentSettingsRequest");
    RegisterRequest::export().expect("export RegisterRequest");
    LoginRequest::export().expect("export LoginRequest");
    RefreshRequest::export().expect("export RefreshRequest");
    LogoutRequest::export().expect("export LogoutRequest");
    AuthResponse::export().expect("export AuthResponse");
    UserResponse::export().expect("export UserResponse");
    UpdateProfileRequest::export().expect("export UpdateProfileRequest");
    OAuthRegisterRequest::export().expect("export OAuthRegisterRequest");
    OAuthRegisterResponse::export().expect("export OAuthRegisterResponse");
    OAuthApproveRequest::export().expect("export OAuthApproveRequest");
    OAuthDecision::export().expect("export OAuthDecision");
    OAuthApproveResponse::export().expect("export OAuthApproveResponse");
    OAuthAuthorizeContext::export().expect("export OAuthAuthorizeContext");
    OAuthErrorResponse::export().expect("export OAuthErrorResponse");
}
