#![forbid(unsafe_code)]

pub mod assignee;
mod auth;

mod actor;
mod agent_chats;
mod analytics;
mod collaboration;
mod coordination;
mod core;
mod daemon_transport;
mod execution;
mod gates;
mod git;
mod integration;
mod lists;
mod mcp;
mod memory;
mod mission_control;
mod oauth;
mod operations;
mod product_genesis;
mod project_hooks;
mod project_orchestration;
mod provider_auth;
mod public_events;
mod repo_review;
mod requests;
mod review_validation;
mod runtime;
mod settings;
mod terminal;
mod work_unit;
mod workflow;

pub use actor::*;
pub use agent_chats::*;
pub use analytics::*;
pub use auth::*;
pub use collaboration::*;
pub use coordination::*;
pub use core::*;
pub use daemon_transport::*;
pub use execution::*;
pub use gates::*;
pub use git::*;
pub use integration::*;
pub use lists::*;
pub use mcp::*;
pub use memory::*;
pub use mission_control::*;
pub use oauth::*;
pub use operations::*;
pub use product_genesis::*;
pub use project_hooks::*;
pub use project_orchestration::*;
pub use provider_auth::*;
pub use public_events::*;
pub use repo_review::*;
pub use requests::*;
pub use review_validation::*;
pub use runtime::*;
pub use settings::*;
pub use terminal::*;
pub use work_unit::*;
pub use workflow::*;

#[test]
#[ignore = "manual type export for the web client"]
fn export_typescript() {
    use ts_rs::TS;

    let out_dir =
        std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../web/src/types/generated");
    std::fs::create_dir_all(&out_dir).expect("create types output directory");
    std::env::set_current_dir(&out_dir).expect("switch to types output directory");

    // These are current target-domain wire contracts. Historical release
    // references are exported only through ProjectRelease's exact dependency
    // closure; storage and migration DTOs are not part of the public barrel.
    TaskType::export().expect("export TaskType");
    WorkMode::export().expect("export WorkMode");
    AgentStatus::export().expect("export AgentStatus");
    ExecutionPurpose::export().expect("export ExecutionPurpose");
    ExecutionStatus::export().expect("export ExecutionStatus");
    StopReason::export().expect("export StopReason");
    ResumePolicy::export().expect("export ResumePolicy");
    ActorRef::export().expect("export ActorRef");
    PublicEventType::export().expect("export PublicEventType");
    PublicEventEnvelope::export().expect("export PublicEventEnvelope");

    CreateProjectRequest::export().expect("export CreateProjectRequest");
    UpdateProjectRequest::export().expect("export UpdateProjectRequest");
    ProjectResponse::export().expect("export ProjectResponse");
    CreateTaskRequest::export().expect("export CreateTaskRequest");
    ReorderSubtasksRequest::export().expect("export ReorderSubtasksRequest");
    UpdateTaskRequest::export().expect("export UpdateTaskRequest");
    TaskResponse::export().expect("export TaskResponse");
    TaskExecutionObservability::export().expect("export TaskExecutionObservability");
    CreateRepoRequest::export().expect("export CreateRepoRequest");
    PrProviderConfigRequest::export().expect("export PrProviderConfigRequest");
    UpdateRepoRequest::export().expect("export UpdateRepoRequest");
    UpdatePrProviderConfigRequest::export().expect("export UpdatePrProviderConfigRequest");
    RepoResponse::export().expect("export RepoResponse");
    PrProviderStatus::export().expect("export PrProviderStatus");
    ArtifactRef::export().expect("export ArtifactRef");
    EvidencePin::export().expect("export EvidencePin");
    ReleaseDecisionReference::export().expect("export ReleaseDecisionReference");
    ReleaseTaskReference::export().expect("export ReleaseTaskReference");
    ReleaseValidationReference::export().expect("export ReleaseValidationReference");
    DiffFileStatus::export().expect("export DiffFileStatus");
    FileDiffSummary::export().expect("export FileDiffSummary");
    DiffStats::export().expect("export DiffStats");
    DiffResponse::export().expect("export DiffResponse");
    DiffEnvelope::export().expect("export DiffEnvelope");
    RepoSyncResponse::export().expect("export RepoSyncResponse");
    FsEntry::export().expect("export FsEntry");
    FsListResponse::export().expect("export FsListResponse");
    BranchListResponse::export().expect("export BranchListResponse");

    TransitionTaskLifecycleRequest::export().expect("export TransitionTaskLifecycleRequest");
    TaskLifecycleState::export().expect("export TaskLifecycleState");
    TaskLifecycleResponse::export().expect("export TaskLifecycleResponse");
    TaskLifecycleTransitionResponse::export().expect("export TaskLifecycleTransitionResponse");
    TaskLifecycleTransitionFactResponse::export()
        .expect("export TaskLifecycleTransitionFactResponse");
    CreateTaskGateRequest::export().expect("export CreateTaskGateRequest");
    ReviseGatePolicyRequest::export().expect("export ReviseGatePolicyRequest");
    TaskGateResponse::export().expect("export TaskGateResponse");
    GatePolicyRevisionResponse::export().expect("export GatePolicyRevisionResponse");
    GateResponse::export().expect("export GateResponse");
    GateEvaluationInputResponse::export().expect("export GateEvaluationInputResponse");
    GateEvaluationResponse::export().expect("export GateEvaluationResponse");
    MergeAfterGateRequest::export().expect("export MergeAfterGateRequest");
    MergeAfterGateResponse::export().expect("export MergeAfterGateResponse");

    StartExecutionRequest::export().expect("export StartExecutionRequest");
    FollowUpRequest::export().expect("export FollowUpRequest");
    ClaimOverrides::export().expect("export ClaimOverrides");
    ExecutionResponse::export().expect("export ExecutionResponse");
    ExecutionUsageResponse::export().expect("export ExecutionUsageResponse");
    TaskUsageSummaryResponse::export().expect("export TaskUsageSummaryResponse");
    ExecutionLogKind::export().expect("export ExecutionLogKind");
    ExecutionLogStream::export().expect("export ExecutionLogStream");
    ExecutionLogEntry::export().expect("export ExecutionLogEntry");
    ExecutionLogsResponse::export().expect("export ExecutionLogsResponse");
    StartReviewExecutionRequest::export().expect("export StartReviewExecutionRequest");
    SubmitReviewReportRequest::export().expect("export SubmitReviewReportRequest");
    ReviewReportVerdict::export().expect("export ReviewReportVerdict");
    ReviewExecutionResponse::export().expect("export ReviewExecutionResponse");
    SubmitReviewReportResponse::export().expect("export SubmitReviewReportResponse");
    ValidationRunStatus::export().expect("export ValidationRunStatus");
    ValidationRunResponse::export().expect("export ValidationRunResponse");
    EvidenceResponse::export().expect("export EvidenceResponse");

    CreateTaskRoleRequest::export().expect("export CreateTaskRoleRequest");
    UpdateTaskRoleRequest::export().expect("export UpdateTaskRoleRequest");
    AddRoleMembershipRequest::export().expect("export AddRoleMembershipRequest");
    UpdateRoleMembershipRequest::export().expect("export UpdateRoleMembershipRequest");
    CoordinationMode::export().expect("export CoordinationMode");
    RoleMembershipStatus::export().expect("export RoleMembershipStatus");
    RoleMembershipResponse::export().expect("export RoleMembershipResponse");
    TaskRoleResponse::export().expect("export TaskRoleResponse");

    ArtifactKind::export().expect("export ArtifactKind");
    ArtifactStorageKind::export().expect("export ArtifactStorageKind");
    CollaborationTarget::export().expect("export CollaborationTarget");
    HandoffIntent::export().expect("export HandoffIntent");
    HandoffStatus::export().expect("export HandoffStatus");
    ProposalTargetKind::export().expect("export ProposalTargetKind");
    ProposalTarget::export().expect("export ProposalTarget");
    ProposalStatus::export().expect("export ProposalStatus");
    DecisionOutcome::export().expect("export DecisionOutcome");
    CreateArtifactRequest::export().expect("export CreateArtifactRequest");
    ArtifactResponse::export().expect("export ArtifactResponse");
    ArtifactProducer::export().expect("export ArtifactProducer");
    CreateMessageRequest::export().expect("export CreateMessageRequest");
    MessageResponse::export().expect("export MessageResponse");
    CreateHandoffRequest::export().expect("export CreateHandoffRequest");
    HandoffResponse::export().expect("export HandoffResponse");
    HandoffTransitionRequest::export().expect("export HandoffTransitionRequest");
    CreateProposalRequest::export().expect("export CreateProposalRequest");
    ProposalResponse::export().expect("export ProposalResponse");
    CreateDecisionRequest::export().expect("export CreateDecisionRequest");
    DecisionResponse::export().expect("export DecisionResponse");
    CollaborationListQuery::export().expect("export CollaborationListQuery");

    CreateWorkUnitRequest::export().expect("export CreateWorkUnitRequest");
    CreateWorkUnitProvenance::export().expect("export CreateWorkUnitProvenance");
    UpdateWorkUnitRequest::export().expect("export UpdateWorkUnitRequest");
    AllocateWorkUnitRequest::export().expect("export AllocateWorkUnitRequest");
    TransitionWorkUnitRequest::export().expect("export TransitionWorkUnitRequest");
    AddWorkUnitDependencyRequest::export().expect("export AddWorkUnitDependencyRequest");
    WorkUnitDependencyResponse::export().expect("export WorkUnitDependencyResponse");
    WorkUnitReadinessResponse::export().expect("export WorkUnitReadinessResponse");
    WorkUnitResponse::export().expect("export WorkUnitResponse");
    WorkUnitIntegrationRequest::export().expect("export WorkUnitIntegrationRequest");
    WorkUnitIntegrationResponse::export().expect("export WorkUnitIntegrationResponse");
    WorkUnitIntegrationOutcome::export().expect("export WorkUnitIntegrationOutcome");
    WorkUnitProvenance::export().expect("export WorkUnitProvenance");
    WorkUnitStatus::export().expect("export WorkUnitStatus");

    ProjectHookRule::export().expect("export ProjectHookRule");
    ProjectHookTrigger::export().expect("export ProjectHookTrigger");
    ProjectHookAction::export().expect("export ProjectHookAction");
    ProjectHookRunStatus::export().expect("export ProjectHookRunStatus");
    ProjectHookRunResponse::export().expect("export ProjectHookRunResponse");
    ProjectHookRunsResponse::export().expect("export ProjectHookRunsResponse");
    ProjectRelease::export().expect("export ProjectRelease");
    ReleaseSnapshot::export().expect("export ReleaseSnapshot");
    ReleaseEvidenceAvailability::export().expect("export ReleaseEvidenceAvailability");
    EvidenceAvailability::export().expect("export EvidenceAvailability");
    AcceptanceCheckResultStatus::export().expect("export AcceptanceCheckResultStatus");
    AuthorizationProvenance::export().expect("export AuthorizationProvenance");
    PrincipalKind::export().expect("export PrincipalKind");
    PrincipalRef::export().expect("export PrincipalRef");
    ProjectReleaseListResponse::export().expect("export ProjectReleaseListResponse");

    CreateAgentRequest::export().expect("export CreateAgentRequest");
    UpdateAgentRequest::export().expect("export UpdateAgentRequest");
    AgentResponse::export().expect("export AgentResponse");
    DaemonResponse::export().expect("export DaemonResponse");
    AgentAvailabilityResponse::export().expect("export AgentAvailabilityResponse");
    DiscoveredOptionsResponse::export().expect("export DiscoveredOptionsResponse");
    DiscoveredDaemonResponse::export().expect("export DiscoveredDaemonResponse");
    AgentProfileResponse::export().expect("export AgentProfileResponse");
    SelectAgentProfileRequest::export().expect("export SelectAgentProfileRequest");
    HarnessCapabilities::export().expect("export HarnessCapabilities");
    CapabilitySupport::export().expect("export CapabilitySupport");
    ExecutorTypeDescriptor::export().expect("export ExecutorTypeDescriptor");
    WorkspaceResponse::export().expect("export WorkspaceResponse");

    AgentProviderId::export().expect("export AgentProviderId");
    ProviderCredentialMethod::export().expect("export ProviderCredentialMethod");
    ProviderSupportLevel::export().expect("export ProviderSupportLevel");
    ProviderRuntimeCapability::export().expect("export ProviderRuntimeCapability");
    ProviderCredentialCapability::export().expect("export ProviderCredentialCapability");
    AgentProviderCapability::export().expect("export AgentProviderCapability");
    AgentProviderCapabilitiesResponse::export().expect("export AgentProviderCapabilitiesResponse");
    ProviderEntryAgentRef::export().expect("export ProviderEntryAgentRef");
    ProviderEntryResponse::export().expect("export ProviderEntryResponse");
    CliRuntimeEntryResponse::export().expect("export CliRuntimeEntryResponse");
    ProviderEntriesResponse::export().expect("export ProviderEntriesResponse");
    ProviderEntryTestResponse::export().expect("export ProviderEntryTestResponse");
    CreateProviderEntryRequest::export().expect("export CreateProviderEntryRequest");
    RenameProviderEntryRequest::export().expect("export RenameProviderEntryRequest");
    ProviderAuthorizationState::export().expect("export ProviderAuthorizationState");
    StartProviderAuthorizationRequest::export().expect("export StartProviderAuthorizationRequest");
    CancelProviderAuthorizationRequest::export()
        .expect("export CancelProviderAuthorizationRequest");
    ProviderAuthorizationOperationResponse::export()
        .expect("export ProviderAuthorizationOperationResponse");
    DisconnectCredentialResponse::export().expect("export DisconnectCredentialResponse");
    ProviderUsageWindow::export().expect("export ProviderUsageWindow");
    ProviderUsageResponse::export().expect("export ProviderUsageResponse");

    DaemonProtocolCapabilitiesRequest::export().expect("export DaemonProtocolCapabilitiesRequest");
    DaemonProtocolCapabilities::export().expect("export DaemonProtocolCapabilities");
    ExecutionStartParams::export().expect("export ExecutionStartParams");
    RemoteResolvedCandidate::export().expect("export RemoteResolvedCandidate");
    HarnessCapabilitiesSnapshot::export().expect("export HarnessCapabilitiesSnapshot");
    HarnessInvocation::export().expect("export HarnessInvocation");
    McpConfigActionRequest::export().expect("export McpConfigActionRequest");
    McpConfigResponse::export().expect("export McpConfigResponse");
    OAuthRegisterRequest::export().expect("export OAuthRegisterRequest");
    OAuthRegisterResponse::export().expect("export OAuthRegisterResponse");
    OAuthApproveRequest::export().expect("export OAuthApproveRequest");
    OAuthDecision::export().expect("export OAuthDecision");
    OAuthApproveResponse::export().expect("export OAuthApproveResponse");
    OAuthAuthorizeContext::export().expect("export OAuthAuthorizeContext");
    OAuthErrorResponse::export().expect("export OAuthErrorResponse");

    CreateTerminalSessionRequest::export().expect("export CreateTerminalSessionRequest");
    ResizeTerminalSessionRequest::export().expect("export ResizeTerminalSessionRequest");
    TerminalAttachTokenResponse::export().expect("export TerminalAttachTokenResponse");
    TerminalAvailability::export().expect("export TerminalAvailability");
    TerminalSessionResponse::export().expect("export TerminalSessionResponse");
    TerminalSessionStatus::export().expect("export TerminalSessionStatus");
    TerminalServerFrame::export().expect("export TerminalServerFrame");

    SettingsResponse::export().expect("export SettingsResponse");
    ForgeSettingResponse::export().expect("export ForgeSettingResponse");
    UpdateSettingsRequest::export().expect("export UpdateSettingsRequest");
    LoopbackOwner::export().expect("export LoopbackOwner");
    ProviderRevocationStatus::export().expect("export ProviderRevocationStatus");
    DecisionRecordState::export().expect("export DecisionRecordState");
    UpdateForgePathsRequest::export().expect("export UpdateForgePathsRequest");
    UpdateServerSettingsRequest::export().expect("export UpdateServerSettingsRequest");
    UpdateWorkspaceSettingsRequest::export().expect("export UpdateWorkspaceSettingsRequest");
    UpdateAgentSettingsRequest::export().expect("export UpdateAgentSettingsRequest");
    RegisterRequest::export().expect("export RegisterRequest");
    LoginRequest::export().expect("export LoginRequest");
    RefreshRequest::export().expect("export RefreshRequest");
    LogoutRequest::export().expect("export LogoutRequest");
    AuthResponse::export().expect("export AuthResponse");
    UserResponse::export().expect("export UserResponse");
    UpdateProfileRequest::export().expect("export UpdateProfileRequest");
    CreateTokenRequest::export().expect("export CreateTokenRequest");
    TokenResponse::export().expect("export TokenResponse");
    AddMemberRequest::export().expect("export AddMemberRequest");
    UpdateMemberRoleRequest::export().expect("export UpdateMemberRoleRequest");
    ProjectMemberResponse::export().expect("export ProjectMemberResponse");
    UserSearchResult::export().expect("export UserSearchResult");

    CreateIntegrationRequest::export().expect("export CreateIntegrationRequest");
    PatchIntegrationRequest::export().expect("export PatchIntegrationRequest");
    IntegrationResponse::export().expect("export IntegrationResponse");
    CreateExternalLinkRequest::export().expect("export CreateExternalLinkRequest");
    ExternalLinkResponse::export().expect("export ExternalLinkResponse");
    SyncTriggerResponse::export().expect("export SyncTriggerResponse");
    OperatorSeverity::export().expect("export OperatorSeverity");
    OperatorStatusResponse::export().expect("export OperatorStatusResponse");
    ActiveExecutionSummary::export().expect("export ActiveExecutionSummary");
    BlockedTaskSummary::export().expect("export BlockedTaskSummary");
    DaemonIssueSummary::export().expect("export DaemonIssueSummary");
    DaemonPressureSummary::export().expect("export DaemonPressureSummary");
    AgentPressureSummary::export().expect("export AgentPressureSummary");
    WorkspaceCleanupSummary::export().expect("export WorkspaceCleanupSummary");
    RetryPressureSummary::export().expect("export RetryPressureSummary");
    TokenTotalsSummary::export().expect("export TokenTotalsSummary");
    UsageSummary::export().expect("export UsageSummary");
    OperationsRefreshResponse::export().expect("export OperationsRefreshResponse");
    RecentErrorSummary::export().expect("export RecentErrorSummary");
    NotificationResponse::export().expect("export NotificationResponse");
    UnreadCountResponse::export().expect("export UnreadCountResponse");
    EffectiveExecutionPolicy::export().expect("export EffectiveExecutionPolicy");
    ErrorResponse::export().expect("export ErrorResponse");
}
